"""initial_schema_with_uuid_and_indices

Revision ID: 63ceb878a60b
Revises: 
Create Date: 2026-10-03 13:00:51.205749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63ceb878a60b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match_results', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_index('uq_match_results_profile_scheme', table_name='match_results')
    op.create_unique_constraint('uq_match_results_profile_scheme', 'match_results', ['profile_id', 'scheme_id'])
    op.alter_column('user_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint('user_profiles_uuid_key', 'user_profiles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_profiles_uuid_key', 'user_profiles', ['uuid'])
    op.alter_column('user_profiles', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint('uq_match_results_profile_scheme', 'match_results', type_='unique')
    op.create_index('uq_match_results_profile_scheme', 'match_results', ['profile_id', 'scheme_id'], unique=True)
    op.alter_column('match_results', 'created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
